# Project information
site_name: Notes, Code, and Solutions for Princeton Algorithms Course

# Configuration
theme:
  name: material
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - toc.integrate

# Plugins
plugins:
  - search
  - tags:
      tags_file: tags.md

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home: index.md
  - 4. Graphs:
    - ch4-graphs/index.md
    - 4.1 Undirected Graph: ch4-graphs/ch4-1-undirected-graphs/undirected-graphs.md
    - 4.2 Directed Graphs: ch4-graphs/ch4-2-directed-graphs/directed-graphs.md
  - Tag: tags.md